InvestApp/urls.py
"""Defines URL patterns for your Application."""
from django.conf.urls import url

from . import views

urlpatterns = [
     # Home page
     url(r'^$', views.index, name='index'),

    # List of all ETFs.
    url(r'^etf_list/$', views.etf_list, name='etf_list'),

    # Page for single ETF details
    url(r'^etf_list/(?P<etf_id>\d+)/$', views.etf_details, name='etf_details'),

    # Page for adding a new ETF
    url(r'^new_etf/$', views.new_etf, name='new_etf'),

    # Page for editing an ETF
    url(r'^edit_etf/(?P<etf_id>\d+)/$', views.edit_etf, name='edit_etf'),

    # Deleting ETFs
    url(r'^delete_etf/(?P<etf_id>\d+)/$', views.delete_etf, name='delete_etf'),

    # Update Individual ETF Price
    url(r'^update_etf_price/(?P<etf_id>\d+)/$', views.update_etf_price, name='update_etf_price'),

    # Refresh All ETF Prices
    url(r'^refresh_etf_prices/$', views.refresh_etf_prices, name='refresh_etf_prices'),

    # List of all Accounts.
    url(r'^accounts_list/$', views.accounts_list, name='accounts_list'),

    # Pager for Account Details
    url(r'^accounts_list/(?P<account_id>\d+)/$', views.account_details, name='account_details'),

    # Page for adding a new Account
    url(r'^new_account/$', views.new_account, name='new_account'),

    # Deleting Accounts
    url(r'^delete_account/(?P<account_id>\d+)/$', views.delete_account, name='delete_account'),

    # Page for editing an Account
    url(r'^edit_account/(?P<account_id>\d+)/$', views.edit_account, name='edit_account'),

    # Page for adding an ETF to an Account
    url(r'^addETFtoAccount/(?P<account_id>\d+)/$', views.addETFtoAccount, name='addETFtoAccount'),

]

InvestProject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('InvestApp.urls', namespace='investapp')),
]

users/urls.py
""" Defines URL patterns for users"""

from django.conf.urls import url
from django.contrib.auth.views import login

from .import views

urlpatterns = [
    # Login page
    url(r'^login/$', login, {'template_name': 'users/login.html'},
        name='login'),
    # Logout page
    url(r'^logout/$', views.logout_view, name='logout'),
    # Registration page
    url(r'^register/$', views.register, name='register'),
]

InvestApp/models.py
from django.db import models
from django.contrib.auth.models import User


class etf(models.Model):
    """The ETF model"""
    owner = models.ForeignKey(User)
    symbol = models.CharField(max_length=4)
    name = models.CharField(max_length=200)
    currentPrice = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    def __str__(self):
        """Return a string representation of the model."""
        return self.symbol


class account(models.Model):
    owner = models.ForeignKey(User)
    name = models.CharField(max_length=200)
    type = models.CharField(max_length=200)
    totalCashValue = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    totalStockValue = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    totalAccountValue = models.DecimalField(max_digits=6, decimal_places=2, default=0)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name


class accountBreakdown(models.Model):
    accountID = models.ForeignKey(account)
    etfID = models.ForeignKey(etf)
    quantity = models.IntegerField()
    owner = models.ForeignKey(User)

    def __str__(self):
        """Return a string representation of the model."""
        return '%s %s %s'%(self.accountID, self.etfID, self.quantity)

InvestApp/forms.py
from django import forms

from .models import etf, account, accountBreakdown

class etf_form(forms.ModelForm):
    class Meta:
        model = etf
        fields = ['symbol', 'name']
        labels = {'symbol': 'Symbol:', 'name': 'Name:'}

class account_form(forms.ModelForm):
    class Meta:
        model = account
        fields = ['name', 'type']
        labels = {'name': 'Account Name: ', 'type': 'Account Type'}

class addETFtoAccount_form(forms.ModelForm):
    class Meta:
        model = accountBreakdown
        fields = ['etfID', 'quantity']
        labels = {'etfID': 'ETF', 'quantity': 'Quantity'}

InvestApp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from .models import etf, account, accountBreakdown
from .forms import etf_form, account_form, addETFtoAccount_form

# Import for Google Finance API Query
import requests, urllib, json

def index(request):
    """The home page for your Application"""
    return render(request, 'investapp/index.html')


@login_required
def etf_list(request):
    """Show list of all ETFs"""
    etf_list = etf.objects.filter(owner=request.user).order_by('symbol')
    context = {'etf_list': etf_list}
    return render(request, 'investapp/etf_list.html', context)


@login_required
def etf_details(request, etf_id):
    """Show a single ETF and its attributes"""
    e = get_object_or_404(etf, id=etf_id)
    if e.owner != request.user:
        raise Http404
    context = {'etf': e}
    return render(request, 'investapp/etf_details.html', context)


@login_required
def new_etf(request):
    """ Add a new ETF"""
    if request.method != 'POST':
        # No data submitted; create a blank form
        form = etf_form()
    else:
        # POST data submitted; process data
        form = etf_form(request.POST)
        if form.is_valid():
            new_etf = form.save(commit=False)
            new_etf.owner = request.user
            new_etf.save()
            return HttpResponseRedirect(reverse('investapp:etf_list'))

    context = {'form': form}
    return render(request, 'investapp/new_etf.html', context)


@login_required
def edit_etf(request, etf_id):
    """ Edit existing ETF"""
    etf_to_edit = get_object_or_404(etf, id=etf_id)
    if etf_to_edit.owner != request.user:
        raise Http404
    if request.method != 'POST':
        # No data submitted; create a blank form
        form = etf_form(instance=etf_to_edit)
    else:
        # POST data submitted; process data
        form = etf_form(instance=etf_to_edit, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('investapp:etf_details',
                                                args=[etf_id]))
    context = {'etf': etf_to_edit, 'form': form}
    return render(request, 'investapp/edit_etf.html', context)


@login_required
def delete_etf(request, etf_id):
    """ Delete existing ETF """
    etf_to_delete = get_object_or_404(etf, id=etf_id)
    etf_to_delete.delete()
    return HttpResponseRedirect(reverse('investapp:etf_list'))


@login_required
def update_etf_price(request, etf_id):
    etf_to_update = get_object_or_404(etf, id=etf_id)

    # Make an API call and store the response.
    url = 'http://finance.google.com/finance/info?client=ig&q=NYSEARCA:' + etf_to_update.symbol
    res = urllib.request.urlopen(url)
    content = urllib.request.urlopen(url).read()
    content = str(content)
    contentClean = content.replace("//", "").replace('\\n', '').replace("b'", "").replace("[", "").replace("]", "").replace(" ", "")
    contentClean = contentClean[:-1]
    jsonRes = json.loads(contentClean)
    new_Price = (jsonRes['l_cur'])

    etf_to_update.currentPrice = new_Price
    etf_to_update.save()
    return HttpResponseRedirect(reverse('investapp:etf_details', args=[etf_id]))


@login_required
def refresh_etf_prices(request):

    # For loop to iterate over etf_list
    for etf_to_update in etf.objects.all():
        # Make an API call and store the response.
        url = 'http://finance.google.com/finance/info?client=ig&q=NYSEARCA:' + etf_to_update.symbol
        res = urllib.request.urlopen(url)
        content = urllib.request.urlopen(url).read()
        content = str(content)
        contentClean = content.replace("//", "").replace('\\n', '').replace("b'", "").replace("[", "").replace("]", "").replace(" ", "")
        contentClean = contentClean[:-1]
        jsonRes = json.loads(contentClean)
        new_Price = (jsonRes['l_cur'])

        etf_to_update.currentPrice = new_Price
        etf_to_update.save()

    return HttpResponseRedirect(reverse('investapp:etf_list'))


@login_required
def accounts_list(request):
    """Show list of all Accounts"""
    accounts_list = account.objects.filter(owner=request.user).order_by('id')
    context = {'accounts_list': accounts_list}
    return render(request, 'investapp/accounts_list.html', context)


@login_required
def new_account(request):
    """ Add a new Account"""
    if request.method != 'POST':
        # No data submitted; create a blank form
        form = account_form()
    else:
        # POST data submitted; process data
        form = account_form(request.POST)
        if form.is_valid():
            new_account = form.save(commit=False)
            new_account.owner = request.user
            new_account.save()
            return HttpResponseRedirect(reverse('investapp:accounts_list'))
    context = {'form': form}
    return render(request, 'investapp/new_account.html', context)


@login_required
def account_details(request, account_id):
    """Show a single Account and its attributes"""
    acc = get_object_or_404(account, id=account_id)
    stock_list = accountBreakdown.objects.filter(owner=request.user, accountID=account_id).order_by('id')
    if acc.owner != request.user:
        raise Http404
    context = {'acc': acc, 'stock_list': stock_list}
    return render(request, 'investapp/account_details.html', context)


@login_required
def delete_account(request, account_id):
    """ Delete existing Account """
    account_to_delete = get_object_or_404(account, id=account_id)
    account_to_delete.delete()
    return HttpResponseRedirect(reverse('investapp:accounts_list'))


@login_required
def edit_account(request, account_id):
    """ Edit existing ETF"""
    account_to_edit = get_object_or_404(account, id=account_id)
    if account_to_edit.owner != request.user:
        raise Http404
    if request.method != 'POST':
        # No data submitted; create a blank form
        form = account_form(instance=account_to_edit)
    else:
        # POST data submitted; process data
        form = account_form(instance=account_to_edit, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('investapp:account_details',
                                                args=[account_id]))
    context = {'account': account_to_edit, 'form': form}
    return render(request, 'investapp/edit_account.html', context)


@login_required
def addETFtoAccount(request, account_id):
    """ Add an ETF to Account"""
    account_to_edit = get_object_or_404(account, id=account_id)
    if account_to_edit.owner != request.user:
        raise Http404
    if request.method != 'POST':
        # No data submitted; create a blank form
        form = addETFtoAccount_form()
    else:
        # POST data submitted; process data
        form = addETFtoAccount_form(request.POST)
        if form.is_valid():
            addedETF = form.save(commit=False)
            addedETF.owner = request.user
            addedETF.accountID = account_to_edit
            addedETF.save()
            return HttpResponseRedirect(reverse('investapp:account_details', args=[account_id]))
    context = {'account': account_to_edit, 'form': form}
    return render(request, 'investapp/addETFtoAccount.html', context)

InvestApp/templates/investapp/account_details.html
{% extends "investapp/base.html" %}

{% block content %}

  <p>
    <a href="{% url 'investapp:edit_account' acc.id %}">Edit</a>
    <a href="{% url 'investapp:delete_account' acc.id %}">Delete</a>
  </p>

  <p><b>Account Details</b></p>

  <ul>
    <li>Account Name: {{ acc.name }}</li>
    <li>Account: {{ acc.type }}</li>
  </ul>

  <p><b>Account Breakdown</b></p>

  <table>
    <tr>
      <th>ETF_ID</th>
      <th>ETF Symbol</th>
      <th>Quantity</th>
    </tr>
    {% for stock in stock_list %}
    <tr>
      <td>{{ stock.etfID.id }}</td>
      <td>{{ stock.etfID.symbol }}</td>
      <td>{{ stock.quantity }}</td>
    {% empty %}
      <li>No stocks have been added yet.</li>
    {% endfor %}
    </tr>
  </table>

  <br>
    <a href="{% url 'investapp:addETFtoAccount' acc.id%}">Add an ETF to an Account:</a>

{% endblock content %}

InvestApp/templates/investapp/accounts_list.html
{% extends "investapp/base.html" %}

{% block content %}

  <p>List of Accounts</p>

  <table>
    <tr>
      <th>Account Name</th>
      <th>Account Type</th>
    </tr>
    {% for account in accounts_list %}
    <tr>
      <td><a href="{% url 'investapp:account_details' account.id %}">{{ account.name }}</a></td>
      <td>{{ account.type }}</td>
    {% empty %}
      <li>No Accounts have been added yet.</li>
    {% endfor %}
    </tr>
  </table>
  <br>
    <a href="{% url 'investapp:new_account' %}">Add a new Account:</a>

{% endblock content %}

InvestApp/templates/investapp/addETFtoAccount.html
{% extends "investapp/base.html" %}

{% block content %}
  <p>Add ETF to an Account:</p>
  <form action="{% url 'investapp:addETFtoAccount' account.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add ETF</button>
  </form>

{% endblock content %}

InvestApp/templates/investapp/base.html
<p>
  <a href="{% url 'investapp:index' %}">Home</a> -
  <a href="{% url 'investapp:accounts_list' %}">Accounts List</a> -
  <a href="{% url 'investapp:etf_list' %}">ETF List</a> -
  {% if user.is_authenticated %}
    Hello, {{ user.username }}.
    <a href="{% url 'users:logout' %}">Log Out</a>
  {% else %}
    <a href="{% url 'users:register' %}">Register</a> -
    <a href="{% url 'users:login' %}">Log In</a>
  {% endif %}
</p>

{% block content %}{% endblock content %}

InvestApp/templates/investapp/edit_account.html
{% extends "investapp/base.html" %}

{% block content %}

<p><b>Edit Account</b></p>

  <form action="{% url 'investapp:edit_account' account.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>save changes</button>
  </form>

{% endblock content %}

InvestApp/templates/investapp/edit_etf.html
{% extends "investapp/base.html" %}

{% block content %}

<p>ETF: {{ symbol }}</p>

  <form action="{% url 'investapp:edit_etf' etf.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>save changes</button>
  </form>

{% endblock content %}

InvestApp/templates/investapp/etf_details.html
{% extends "investapp/base.html" %}

{% block content %}

  <p>
    <a href="{% url 'investapp:edit_etf' etf.id %}">Edit</a>
    <a href="{% url 'investapp:delete_etf' etf.id %}">Delete</a>
    <a href="{% url 'investapp:update_etf_price' etf.id %}">Update Price</a>
  </p>

  <p><b>ETF Details</b></p>

  <ul>
    <li>Symbol: {{ etf.symbol }}</li>
    <li>Name: {{ etf.name }}</li>
    <li>Current Price: ${{ etf.currentPrice }}</li>
  </ul>

{% endblock content %}

InvestApp/templates/investapp/etf_list.html
{% extends "investapp/base.html" %}

{% block content %}

  <p>List of ETFs</p>

  <table>
    <tr>
      <th>Symbol</th>
      <th>Name</th>
      <th>Current Price</th>
    </tr>
    {% for etf in etf_list %}
    <tr>
      <td><a href="{% url 'investapp:etf_details' etf.id %}">{{ etf.symbol }}</a></td>
      <td>{{ etf.name }}</td>
      <td>{{ etf.currentPrice }}</td>
    {% empty %}
      <li>No ETFs have been added yet.</li>
    {% endfor %}
    </tr>
  </table>
  <br>
    <a href="{% url 'investapp:refresh_etf_prices' %}">Refresh ETF Prices</a>
  <br>
    <a href="{% url 'investapp:new_etf' %}">Add a new ETF:</a>

{% endblock content %}

InvestApp/templates/investapp/index.html
{% extends "investapp/base.html" %}

{% block content %}
  <p>This is the InvestApp homepage</p>
{% endblock content %}

InvestApp/templates/investapp/new_account.html
{% extends "investapp/base.html" %}

{% block content %}
  <p>Add a new Account:</p>
  <form action="{% url 'investapp:new_account' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add Account</button>
  </form>

{% endblock content %}

InvestApp/templates/investapp/new_etf.html
{% extends "investapp/base.html" %}

{% block content %}
  <p>Add a new ETF:</p>
  <form action="{% url 'investapp:new_etf' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add ETF</button>
  </form>

{% endblock content %}